[profile.default]
src = 'src'
out = 'out'
libs = ['lib', 'shim/Mock']
solc_version = "0.8.19"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "filecoin-solidity/=lib/filecoin-solidity/contracts/v0.8/",
  "src/=src/",
  "shim/=shim/Mock/",
  "interfaces/=src/interfaces/"
]

[profile.fevm]
src = 'src'
out = 'out-fevm'
libs = ['lib', 'shim/FEVM']
solc_version = "0.8.17"
remappings = [
  "ds-test/=lib/forge-std/lib/ds-test/src/",
  "forge-std/=lib/forge-std/src/",
  "solmate/=lib/solmate/src/",
  "filecoin-solidity/=lib/filecoin-solidity/contracts/v0.8/",
  "src/=src/",
  "shim/=shim/FEVM/",
  "interfaces/=src/interfaces/"
]
optimizer_details.yul = false

[rpc_endpoints]
filecoin = "https://api.node.glif.io/"

[fuzz]
runs = 1024

# See more config options https://github.com/foundry-rs/foundry/tree/master/config